apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ridho-wp
spec:
  storageClassName: rook-cephfs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
