apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: ridho-wp
spec:
  storageClassName: rook-cephfs
  capacity: 
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www"
